name: Sanity Test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - name: Lint
        run: npm run lint
